### ISSUE TITLE
Global SPC in GRID creates an Analysis.

### ISSUE THREAD

**Issue by ThomasAbballe** [Alneos/vega#15]
VEGA can now (or now again) translate "mesh-only" file. However, in NASTRAN, if some GRID points have CD specified, a "dummy" analysis is created to to host the corresponding "common constraint set". It's odd that a common needs to create a specific analysis to work ;)

It's a small bug, without consequences that i know of. I'm noting here to not forget.

**Comment by ldallolio** [comment]
I agree (and I like as usual your point of view) : it is odd to have to define an analysis to add a Nastran CD :-)

**Comment by ldallolio-irt** [comment]
Should be fixed now (added a unit test and a functional test for nastran). This was not related to CD but in general the parser added one analysis in parseExecutiveSection when it was not specified, now commented out:

//                if (!subCaseFound) {
//                    addAnalysis(tok, model, context);
//                }
