### ISSUE TITLE
Doxygen without LaTeX

### ISSUE THREAD

**Issue by ThomasAbballe** [Alneos/vega#19]
Hi all,

My compilation machines have Doxygen 1.8.5 but not LaTeX. The latest versions seems to need it to build pdf. I have plenty of errors:

> sh: epstopdf: command not found
error: Problems running epstopdf. Check your TeX installation!

I blame d3eecc9960edf7e73ed94ee4017934112151e0cb for this  new behavior, but I'm not sure. 

Anyway, is there a way to disable the pdf compilation of DOxygen if LaTeX is not installed ? Or to allow the user to manually disable it ?

Cheers,

**Comment by ldallolio-irt** [comment]
Hi Thomas,

Fixed in 5a457c1813568a342056776d4a12372468432936

Also removed, in a later commit, man pages generation
