### ISSUE TITLE
Control commands are no longer converted to uppercase

### ISSUE THREAD

**Issue by ThomasAbballe** [Alneos/vega#22]
Push c815f3d2f21814c044dc73f14edfab4064e969f1 added a regression to the NASTRAN parser. The control commands (spc, load) are not converted to uppercase when they are "global", i.e outside the scope of an analysis.
See ASET-17 example, from the System-X base, for an example to this bug

**Comment by ldallolio** [comment]
Should be fixed in c0a8baf57f2f4476e8d1e6a93d16924adb897d0c and tested in fa9b32cd7d5724658bc2d9a56e6f44bcb3728b34 closing
