### ISSUE TITLE
ATOI error with SET on several lines

### ISSUE THREAD

**Issue by ThomasAbballe** [Alneos/vega#24]
There is an issue with the parsing of the Nastran control command SET. It seems that the version c815f3d does not support a set which is defined on several lines, which is perfectly valid.

> SET 1 = 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708,
>    1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716 
> 

It raises an atoi conversion error and quits vega.

**Comment by ThomasAbballe** [comment]
See CYCLIC2-17, from the System-X base, for an example to this bug.
A specific example to test the translation of the SET control command should be made

**Comment by ldallolio** [comment]
Solved in 8ca82cdb1b9a5c6c0fd9f4cf57501427dfa88a9a CYCLIC2-17 test is passing, added unit test "test_issue24_multilineset" in NastranParser_test
