### ISSUE TITLE
Can't translate Nastran CONM2 with coordinate systems

### ISSUE THREAD

**Issue by ThomasAbballe** [Alneos/vega#28]
Hi all,

The latest versions crashed when translating Nastran files where there are coordinate systems (CORD2R, but I suspect other too) on nodal masses (CONM2). The error message is:

```
terminate called after throwing an instance of 'std::logic_error'
  what():  Mismatch in coordinate system: Position 608 not found
```

I attach here an example.
[grav-coord.nas.txt](https://github.com/Alneos/vega/files/4244248/grav-coord.nas.txt)

**Comment by ldallolio-irt** [comment]
Bug fixed, added unit test and functional test (passing for Aster, running disabled for Systus, maybe because of missing Topaze fix?). The problem should have been present only for CONM1 and CONM2 cells.
