### ISSUE TITLE
Création d'une compilation Windows

### ISSUE THREAD

**Issue by StephaneBoucher** [Alneos/vega#30]
Bonjour,

je souhaiterais compiler ce développement pour une utilisation sous Windows.
Je suis novice en la matière et mes premiers essais (en suivant le readme) sont un échec.
J'ai tenté la compilation avec visual Studio pour commencer mais il manque trop de librairies.
La compilation sous ubuntu semble figée...

Pourriez-vous me guider dans ces étapes de compilation ?
Je vous remercie par avance.

**Comment by ThomasAbballe** [comment]
Bonjour,

Avez-vous essayer via Cygwin? C'est la méthode que j’utilise quotidiennement pour avoir une version Windows. 
C'est normalement intégré aux sources VEGA. La seule difficulté rencontrée devrait être de lier correctement boost : j'ai du copier/coller quelques librairies que cmake ne trouvait pas chez moi. 

Hope it helps

**Comment by StephaneBoucher** [comment]
Bonjour,

j'ai réussi à faire la compilation (avec une grande aide de Luca j'avoue). Je vous remercie pour votre aide.
