### ISSUE TITLE
Cmake profiles for release and debug

### ISSUE THREAD

**Issue by ThomasAbballe** [Alneos/vega#4]
Hi all,

As of today, they are only two available cmake profiIes: Debug (dynamic compilation) and Release (static compilation). I think it would be nice to distinguished the type of compilation (dynamic or static) from the use of compilation (debug or release). For example, a release version would not use valgrind, be it in Linux or Cygwin. 

I propose to have the four profiles:
- SDebug (Static Debug)
- SRelease (Static Release)
- DDebug (Dynamic Debug)
- DRelease (Dynamic Release)

What do you think of it?  Will it suit your need? Are the name clear?
Cheers,
Thomas

**Comment by ldallolio** [comment]
Debug<->Dynamic and Release<->Static were motivated by:
- we tried to keep it simple : Release is for the customers, Debug is for development (or for customers with unclear problems)
- you need to link dynamically to debug using valgrind
- we could only understand two use cases : static link for distribution (linux or windows), all dynamic for development (faster build, smaller binary, in particular for tests)
- more configurations in cmake means more tests and more coding

Other than that, why not :-)

**Comment by ThomasAbballe** [comment]
Here is a dot-to-dot answer:
- I completely support your first point.
- I'll skip Static Debug if there is no need for. 
- I need a Dynamic release for my customers.
- Tests should mostly (if not only!) done on release versions. As for more code, meh, it's the way of life ;)

I'll work a bit on the subject, and come back with more info/experience/solution on the topic.

**Comment by ThomasAbballe** [comment]
Okay. Changes implemented in the commit  cc81e35. 
- I implemented the four category, for the sake of the completion. 
- All debug code should know be put between `#if defined VDEBUG` macros.
- Default behaviour stay the same, but it is name now "DDebug".
- I updated the Travis script, which should work as before.

Let me know if something broke!

**Comment by ThomasAbballe** [comment]
Finished, i hope, with 886510bd73dc2f133155c3b87643ca5722d25b2c
